driver_config:
    uframe_agent_url: http://uframe:12572/instrument
    scenario: PARAD
    module: mi.instrument.satlantic.par_ser_600m.ooicore.driver
    class: InstrumentDriver
    command_port: 40005
    event_port: 50005
    host: 192.168.56.101
port_agent_config:
    addr: 69.196.58.141
    port: 13009
    cmd_port: 12009
startup_config:
    parameters: